apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: openmeme
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: openmeme
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
