apiVersion: v1
kind: Namespace
metadata:
  name: openmeme
  labels:
    app.kubernetes.io/part-of: openmeme
  annotations:
    # Rancher: assign to project via UI or set field.cattle.io/projectId
    field.cattle.io/projectId: "local:p-openmeme"
