apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: openmeme
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: openmeme
spec:
  # ClusterIP: postgres is only reachable within the namespace
  type: ClusterIP
  clusterIP: None   # Headless service — required for StatefulSet DNS
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
