apiVersion: v1
kind: ServiceAccount
metadata:
  name: memes-api
  namespace: openmeme
  labels:
    app.kubernetes.io/name: memes-api
    app.kubernetes.io/part-of: openmeme
automountServiceAccountToken: false
